"""Generated per-detector rule table (item 202; roadmap Stage 33 D4).

Renders ``docs/aide/rules.generated.md``: one row per registered rule
detector saying the question it asks, the path it reads, when it fires, its
effective default and the failure modes it serves. Nothing else says what a
rule *decides*: ``failure_modes.generated.md`` and the conformance report say
which mode a rule serves, and the decision itself lived only in module
docstrings and ``default_config.yaml`` (insights.md, queue-022 review,
2026-09-22).

Sources: the rule registry (``iter_rules``), each detector's authored
``question`` / ``fires_when`` / ``params`` (``RuleDetector``, read-only
documentation metadata), the bundled ``default_config.yaml`` and
``failure_modes.modes_for_detector``. Regenerate with
``python -m segfacet.rule_table``.

Scope fence: no JSON twin; no severity column; ``bounds``' per-group
hand-set fallback bounds and each rule's ``condition_opt_ins`` are not
rendered (item 202 spec, Left open).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable, Optional

__all__ = ["MD_PATH", "render_markdown", "main"]

_REPO_ROOT = Path(__file__).resolve().parents[2]
MD_PATH = _REPO_ROOT / "docs" / "aide" / "rules.generated.md"


def render_markdown(config=None) -> str:
    """Render the rule table; ``config=None`` means the bundled config."""
    import segfacet.heuristics  # noqa: F401  (registers the rules)
    from segfacet.config import bundled_default_config
    from segfacet.failure_modes import _md_escape, modes_for_detector
    from segfacet.heuristics.rule import iter_rules

    if config is None:
        config = bundled_default_config()

    lines = [
        "# Rule Detectors",
        "",
        "Generated by `python -m segfacet.rule_table` from each registered "
        "rule's `mode_declaration` and the bundled `default_config.yaml`. "
        "Do not edit by hand.",
        "",
        "| Rule | Detector | Question | Reads | Fires when | Default | Modes |",
        "|---|---|---|---|---|---|---|",
    ]
    for rule in iter_rules():
        decl = rule.mode_declaration
        condition_paths = [
            cp.path for cp in decl.consumed_paths if cp.role == "condition-signal"
        ]
        for det in decl.detectors:
            paths = list(det.signal_paths) or condition_paths
            reads = ", ".join(f"`{p}`" for p in paths) or "(none declared)"
            default = (
                "; ".join(
                    f"`{key}` = "
                    f"{json.dumps(config.rule_param(rule.rule_id, key, default=code_default))}"
                    for key, code_default in det.params
                )
                or "(none)"
            )
            modes = ", ".join(
                str(m) for m in modes_for_detector(rule.rule_id, det.detector_id)
            ) or "none"
            cells = [
                f"`{rule.rule_id}`",
                f"`{det.detector_id}`",
                _md_escape(det.question),
                _md_escape(reads),
                _md_escape(det.fires_when),
                _md_escape(default),
                modes,
            ]
            lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"


def main(argv: Optional[Iterable[str]] = None) -> int:
    """``python -m segfacet.rule_table [--md PATH]``; writes through
    ``Path.write_bytes`` so no platform newline translation applies."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Regenerate the generated rule table (item 202)."
    )
    parser.add_argument("--md", type=Path, default=MD_PATH)
    args = parser.parse_args(list(argv) if argv is not None else None)

    args.md.parent.mkdir(parents=True, exist_ok=True)
    args.md.write_bytes(render_markdown().encode("utf-8"))
    return 0


if __name__ == "__main__":
    import sys

    sys.exit(main())
